### ISSUE TITLE
feature request - skip file-name pattern

### ISSUE THREAD

**Issue by morficus** [kalidasya/sonar-css#4]
It would be neat if there was a configurable property to input filename patterns we want to skip.
this would be particularly useful for CSS libraries that are already minified . so it would be cool to say "skip anything with .min.css or -min.css"

**Comment by spil-tamas** [comment]
this should be handled by sonar-core... there is some exclusion pattern, can you try it and let me know if it does not work?

**Comment by kalidasya** [comment]
yes it seems so there is a file exclusion setting for global and for projects

**Comment by kalidasya** [comment]
@morficus WDYT?

**Comment by morficus** [comment]
yup, that solution would work for me.
I must have missed the "global ignore" section :-p
