### ISSUE TITLE
Would love to use this for Sass

### ISSUE THREAD

**Issue by d-claassen** [kalidasya/sonar-css#5]
I read that this plugin is also able to find issues in *.scss files, but I can't figure out how to activate that feature.

Is it possible to analyse scss files with this plugin? What are the changes that have to be made?

I wouldn't mind if a specific setting would make this plugin only analyse scss files, and no longer analyse css. All our css files have already been changed to scss.

**Comment by spil-tamas** [comment]
Unfortunately the sass part is not complete yet. The basic grammar is there but it is not possible to analyze sass files, only if you change the source (replace all CssParser? (not sure, need to check) reference to it's Sass equivalence). It is not sure it is going to work, it is really experimental. 

I do not have time at the moment to work on it, and even if the grammar is ok, we still need to define the issues what we want to catch. 

If you would like to contribute, but not in coding, it is really welcomed to collect those things (Sass pair of CssLint). The lack of these rules is one of the main reasons why is it still in this phase.

**Comment by d-claassen** [comment]
I've tried to replace the calls to `CssGrammar` with `SassGrammar`. Unfortunately, making this change in the `CssAstScanner` results in 4 failing unit tests. These are:

``` java
org.sonar.css.checks.VendorPrefixWithStandardTest
org.sonar.css.checks.BulletproofFontFaceTest
org.sonar.css.checks.DisallowOverspecificSelectorsTest
org.sonar.css.checks.DisallowUnitsForZeroValuesTest
```

After deleting those tests, I got it compiled and working. Now I notice that several css checks are not working nicely with the sass code. E.g. using `&.classname` results in an 'overqualified elements' issue. I'm unfamiliar with Sonar plugins, so I don't know if such a rule could easily be overwritten to understand that an `&` is acceptable. Comments starting with `//` result in the sonar runner unable to complete.

``` scss
.icon {
    background: url(sprite.png) no-repeat;
    &.icon-heart {
        background-position: -16px 0;
    }
}
```

So, just changing `CssGrammar` to `SassGrammar` sadly isn't the only required step.

**Comment by kalidasya** [comment]
well, the checks probably will not work... they are created for css and not sass, some can work, some can report false positives.

In the future, when sass parsing will be mature enough, and we have sass related checks, it will need it's own rule profile, and the checks will be separated from the css ones. 

But anyway, the sass is not supported by this plugin at the moment, it needs development, so it does not really make sense to use it, what it can do for sure, is to show the sass code in sonar. No special metrics, no complexity, no sass specific checks. I would suggest you to parse the css output now and not the sass.
