### ISSUE TITLE
parse error - "+"

### ISSUE THREAD

**Issue by shin820** [kalidasya/sonar-css#8]
Hi,

18:00:39.445 DEBUG - D:\Program Files (x86)\Jenkins\workspace\Modeling_NewMapbuilder_Design_Frontend_Sonar\Mysoft.MAP2.DynamicModeling.Web\Default_Old.csscan't be analysed. erro:Parse error at line 22 column 5 failed to match all of: whiteSpaces semiColon _ident rCurlyBracket ruleset statement

12:     top: 0;
13:     width: 100%;
14:     height: 127px;
15: }
16: .Content
17: {
18:     width: 100%;
19:     position: absolute;
20:     top: 127px;
21:     bottom: 0px;
22:     +height: expression(parentNode.clientHeight - 127 - 2);
        ^
23:     border-top: 1px solid #898D92;
24:     /_background-color: rgb(226, 230, 235);_/
25: }
26: .UserInfo
27: {
28:  position: absolute;
29:  top: 5px;
30:  right: 10px;
31: }
32: .UserInfo a

Failed at rules:
            /-whiteSpaces consumed from (21, 17) to (22, 4): "\r\n    "
          /-semiColon consumed from (21, 16) to (21, 16): ";"
        /-supDeclaration consumed from (18, 5) to (21, 15): ..."olute;\r\n    top: 127px;\r\n    bottom: 0px"
        | /-semiColon
        | |     /-_ident
        | |   /-ident
        | | /-property
        | +-declaration
        +-supDeclaration consumed from (18, 5) to (22, 4): ..."\n    top: 127px;\r\n    bottom: 0px;\r\n    "
      /-block consumed from (17, 1) to (18, 4): "{\r\n    "
      | /-rCurlyBracket
      +-block consumed from (17, 1) to (22, 4): ..."\n    top: 127px;\r\n    bottom: 0px;\r\n    "
    /-ruleset consumed from (16, 1) to (16, 10): ".Content\r\n"
    +-ruleset consumed from (16, 1) to (22, 4): ..."\n    top: 127px;\r\n    bottom: 0px;\r\n    "
  /-statement
  +-statement consumed from (16, 1) to (22, 4): ..."\n    top: 127px;\r\n    bottom: 0px;\r\n    "
/-stylesheet consumed from (1, 1) to (15, 3): ..."   width: 100%;\r\n    height: 127px;\r\n}\r\n"

**Comment by shin820** [comment]
This plugin is pretty good but i get some parse error. 
I will be very appreciated if these parse issues can be fixed.

**Comment by kalidasya** [comment]
thank you for your report, what is that '+' sign there? is it valid?

**Comment by shin820** [comment]
'+' sign is CSS hack for IE, I think it's valid.

**Comment by kalidasya** [comment]
I heard about the 'star hack' and the 'underscore hack' but never about 'plus hack' (see: https://github.com/stubbornella/csslint/wiki/Rules) thats why I am asking :) also the css2 syntax does not allow + in an ident (http://www.w3.org/TR/CSS2/syndata.html)

**Comment by shin820** [comment]
Hi kalidasya,

Yes, you are right. I tried it in CSSLint, it also parsed error.
So this is a issue from my css file, thanks for your help.

**Comment by kalidasya** [comment]
cool, then I close this
